package com.ldm.prac4;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;
import androidx.lifecycle.ViewModelProvider;
import androidx.navigation.fragment.NavHostFragment;

import com.ldm.prac4.databinding.FragmentSecondBinding;
import com.ldm.prac4.database.TaskEntity;
import com.ldm.prac4.TaskViewModel;

public class CreateTaskFragment extends Fragment {

    private FragmentSecondBinding binding;
    private TaskViewModel taskViewModel;
    private EditText editTextTitle, editTextDescription;

    @Override
    public View onCreateView(
            @NonNull LayoutInflater inflater, ViewGroup container,
            Bundle savedInstanceState
    ) {
        binding = FragmentSecondBinding.inflate(inflater, container, false);
        return binding.getRoot();
    }

    @Override
    public void onViewCreated(@NonNull View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        taskViewModel = new ViewModelProvider(this).get(TaskViewModel.class);

        editTextTitle = binding.editTextTitle;
        editTextDescription = binding.editTextDescription;

        binding.buttonSave.setOnClickListener(v -> {
            String title = editTextTitle.getText().toString();
            String description = editTextDescription.getText().toString();

            if (!title.isEmpty() && !description.isEmpty()) {
                // Create a new TaskEntity
                TaskEntity taskEntity = new TaskEntity(0, title, description);  // ID will be auto-generated by Room

                taskViewModel.insert(taskEntity);

                Toast.makeText(getContext(), "Task Created", Toast.LENGTH_SHORT).show();

                NavHostFragment.findNavController(CreateTaskFragment.this)
                        .navigate(R.id.action_CreateTaskFragment_to_FirstFragment);

                editTextTitle.setText("");
                editTextDescription.setText("");
            } else {
                // Show error message if input fields are empty
                Toast.makeText(getContext(), "Please fill in all fields", Toast.LENGTH_SHORT).show();
            }
        });

        // Set up the Back button click listener
        binding.buttonBack.setOnClickListener(v ->
                NavHostFragment.findNavController(CreateTaskFragment.this)
                        .navigate(R.id.action_CreateTaskFragment_to_FirstFragment)
        );
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        binding = null;  // Clean up binding to avoid memory leaks
    }
}
